# 🧠 Matris Çeşitleri: Sayıların Dünyasındaki Şekiller

## Bir matrisin içindeysen, onun dilini bilmelisin.

Matrisler, sadece satır ve sütun değil;  
Sayıların düzenli biçimde dizildiği,  
verinin yapılandırıldığı,  
ve sistemin mantığının yansıtıldığı soyut dünyadır.


Matrisler, lineer cebirin temel yapı taşlarından biridir ve sayıların dikdörtgen bir tablo şeklinde düzenlenmesidir. Farklı şekil ve özelliklere sahip birçok matris çeşidi vardır. 

## 🔍 Matris Nedir?

Bir matris, sayıların satır ve sütunlara göre sıralandığı bir tablodur:

```
[ 1 2 ]  
[ 3 4 ]
```

Bu 2x2’lik bir kare matristir.  
Satır sayısı = Sütun sayısı → kare matris.  
Farklıysa → dikdörtgen matris.

📌 En genel haliyle:
$$
A_{m \times n} = 
\begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dots & a_{mn}
\end{bmatrix}
$$

Yani:
- m satır var  
- n sütun var  
- Toplamda `m x n` eleman taşıyor


## 📐 Boyutlarına Göre Matrisler

### ✅ Satır Matrisi
Sadece bir satır var.

```
[1 2 3]
```

→ 1x3 boyutlu.  
→ Veri biliminde özellik vektörü olarak kullanılır.

### ✅ Sütun Matrisi
Sadece bir sütun var.

```
[1]  
[2]  
[3]
```

→ 3x1 boyutlu.  
→ Makine öğrenmesinde çıktılar bu şekilde gösterilir.

### ✅ Kare Matris
Satır sayısı = Sütun sayısı

```
[1 2]  
[3 4]
```

→ 2x2 kare matris  
→ Determinant, özdeğer gibi işlemler için gereklidir.

### ✅ Dikdörtgen Matris
Satır ≠ Sütun

```
[1 2 3]  
[4 5 6]
```

→ 2x3 dikdörtgen matris  
→ Gerçek dünya verisi çoğu zaman bu formattadır.

## 🔢 Elemanlarına Göre Matris Türleri

### ❌ Sıfır Matrisi
Her şey sıfır.

```
[0 0]  
[0 0]
```


### ✅ Birim Matris (I)
Ana köşegenler 1, diğerleri 0.

```
[1 0]  
[0 1]
```

📌 Terslenebilir sistemlerde anahtar rol oynar.  
📌 Lineer cebirdeki "etkisiz" elementtir.

### ✅ Köşegen Matris
Sadece ana köşegende değer var.

```
[2 0]  
[0 3]
```


### ✅ Üst Üçgensel Matris
Alt üçgendeki tüm değerler sıfır.

```
[1 2 3]  
[0 4 5]  
[0 0 6]
```

📌 Gauss eliminasyonu sonrası elde edilen formdur.  
📌 Hesaplamaları kolaylaştırır.

### ✅ Alt Üçgensel Matris
Üst üçgende değer yok.

```
[1 0 0]  
[2 3 0]  
[4 5 6]
```

📌 LU ayrıştırma gibi yöntemlerde kullanılır.

### ✅ Skaler Matris
Köşegen üzerinde aynı sayılar var.

```
[5 0]  
[0 5]
```

📌 Tüm yönlerde aynı etki → eşit dağılım

## ⚖️ Özel Yapılar: Simetri, Simetrinin Karşısı, Dönüşüm

### ✅ Simetrik Matris
Transpozu kendisine eşit.

```
[1 2]  
[2 3]
```

👉 `A = Aᵀ` → simetriklik!



### ✅ Ters Simetrik (Çarpık Simetrik) Matris
Transpozu negatifine eşit.

```
[ 0  2 ]  
[-2  0 ]
```

👉 `A = -Aᵀ` → çarpık simetri!


### ✅ İdempotent Matris
Karesi kendisine eşit.

```
[1 0]  
[0 1]
```

👉 `A² = A` → sabit yapılıdır

### ✅ İnvolütif Matris
Karesi birim matrise eşit.

```
[ 1  0 ]  
[ 0 -1 ]
```

👉 `A² = I` → dönüşümlerde kullanılır


### ❌ Tekil (Singüler) Matris
Determinantı sıfır olan kare matris.

```
[1 2]  
[2 4]
```

👉 `det(A) = 0` → tersi yoktur  
👉 Sistem çözülemez!

### ✅ Ortogonal Matris
Transpozu tersine eşit.

```
[ 0  1 ]  
[-1  0 ]
```

👉 `Aᵀ = A⁻¹` → dönüşümlerde koruma sağlar

📌 Bilgisayar grafikleri ve yapay zekada çok önemlidir.

In [1]:
# Python ile Pratik: Matris Türlerini Tanıyalım

import numpy as np

# Satır matrisi
satir = np.array([[1, 2, 3]])
print("Satır Matrisi:\n", satir)

# Sütun matrisi
sutun = np.array([[1], [2], [3]])
print("\nSütun Matrisi:\n", sutun)

# Kare matris
kare = np.array([[1, 2], [3, 4]])
print("\nKare Matris:\n", kare)

# Sıfır matrisi
sifir = np.zeros((2, 2))
print("\nSıfır Matrisi:\n", sifir)

# Birim matris
birim = np.eye(2)
print("\nBirim Matris:\n", birim)

# Köşegen matris
koselen = np.diag([2, 3])
print("\nKöşegen Matris:\n", koselen)

# Transpoz alma
A = np.array([[1, 2], [3, 4]])
A_T = A.T
print("\nOrijinal:\n", A)
print("Transpoze:\n", A_T)

# Simetrik kontrol
simetrik_mi = np.array_equal(A, A_T)
print("\nMatris simetrik mi?", simetrik_mi)

# Ters simetrik kontrol
ters_simetrik_mi = np.array_equal(A, -A_T)
print("Matris ters simetrik mi?", ters_simetrik_mi)

# Determinant kontrol
det = np.linalg.det(kare)
print("\nKare matrisin determinantı:", det)

Satır Matrisi:
 [[1 2 3]]

Sütun Matrisi:
 [[1]
 [2]
 [3]]

Kare Matris:
 [[1 2]
 [3 4]]

Sıfır Matrisi:
 [[0. 0.]
 [0. 0.]]

Birim Matris:
 [[1. 0.]
 [0. 1.]]

Köşegen Matris:
 [[2 0]
 [0 3]]

Orijinal:
 [[1 2]
 [3 4]]
Transpoze:
 [[1 3]
 [2 4]]

Matris simetrik mi? False
Matris ters simetrik mi? False

Kare matrisin determinantı: -2.0000000000000004


## 💡 Neden Bu Kategoriler Önemli?

| Sebep | Açıklama |
|--------|----------|
| ✅ Anlama kolaylığı | Her matris türü farklı bir işlev taşır |
| ✅ Uygulamalarda fark oluşturur | Hangi yöntemi uygulayacağını belirler |
| ✅ Modelleme gücü sağlar | Yapay zeka, fizik, ekonomi modellerinde |
| ✅ Hız kazandırır | Bazı matrisler hızlı işlem yapılmasını sağlar |

📌 Lineer cebirde matris türünü bilmek,  
**modelin nasıl çalıştığını anlamaya** gider.