# 📐 Matris ile İlgili Temel Terimler: Sayıların Dünyasındaki Dil

## Giriş: Matris Nedir?

Matris, sayıların **satır ve sütunlara göre dizilmesidir.**  
Bir tablodur, evet.  
Ama sadece tablo değildir.  
Matris, verinin nasıl işlediğini gösteren **ilk dil**dir.

## 🔍 Matrisin Yapı Taşları

# Matrisle ilgili Terimler

- **Matris:** Sayıların (veya sembollerin) dikdörtgen bir tablo şeklinde düzenlenmesidir.
- **Eleman (Giriş):** Matris içindeki her bir sayıya eleman veya giriş denir.
- **Satır:** Matristeki yatay sıralardır.
- **Sütun:** Matristeki dikey sıralardır.
- **Boyut (Ölçü):** Bir matrisin boyutu, satır sayısı ve sütun sayısı ile belirtilir. Örneğin, _m_ satır ve _n_ sütundan oluşan bir matris _m x n_ boyutundadır.
- **Kare Matris:** Satır ve sütun sayıları eşit olan matrislerdir.
- **Ana Köşegen (Asıl Köşegen):** Bir kare matrisin sol üst köşesinden sağ alt köşesine uzanan elemanlarıdır.
- **Köşegen Elemanları:** Ana köşegen üzerindeki elemanlardır.
- **Köşegen Dışı Elemanlar:** Ana köşegenin dışındaki elemanlardır.

### ✅ Eleman (Giriş)
Matristeki her bir hücredeki sayıya eleman denir.  
Veriler burada saklanır.  
Her eleman, bir gerçekliği taşır.

```
[1 2]  
[3 4]
→ 1, 2, 3, 4 → hepsi birer elemandır.
```


### ✅ Satır
Yatay sıralar.  
Satır sayısı arttıkça, veri boyutu büyür.

```
[1 2 3] ← satır  
[4 5 6]
```


### ✅ Sütun
Dikey sıralar.  
Sütunlar, özelliklerin tahtasıdır.

```
[1 2]  
[3 4]  
↑ ↑ sütun
```


### ✅ Boyut (m x n)
Satır sayısı × Sütun sayısı → m x n  
Örneğin:
- 2x3 matris → 2 satır, 3 sütun  
- 4x4 → kare matris  
- 1x5 → satır matrisi  

📌 Python’da `shape` ile anılır.

### ✅ Kare Matris
Satır = Sütun → dengeli yapı

```
[1 2]  
[3 4]
```

📌 Determinant, özdeğer, rank gibi işlemler için şarttır.

### ✅ Ana Köşegen (Asıl Köşegen)
Sol üstten sağ alta doğru gider.

```
[1 _ ]  
[_ 4]
```

👉 Bu köşegen, iz (trace), köşegen matris, determinant gibi işlemlerde rol oynar.

### ✅ Köşegen Elemanları
Ana köşegende yer alan değerlerdir.

```
[1 0]  
[0 4]
→ 1 ve 4 köşegen elemanlardır.
```


### ✅ Köşegen Dışı Elemanlar
Ana köşegenin dışında kalanlar.

```
[1 2]  
[3 4]
→ 2 ve 3 köşegen dışı elemanlardır.
```


## 🧠 Matris İşlemleri: 

**Matris İşlemleri ve İlgili Terimler:**

- **Matris Toplamı:** Aynı boyuttaki iki matrisin karşılık gelen elemanlarının toplanmasıyla elde edilen matristir.
- **Skalerle Çarpma:** Bir matrisin tüm elemanlarının bir skaler (sayı) ile çarpılmasıdır.
- **Matris Çarpımı:** İki matrisin belirli kurallara göre çarpılmasıyla elde edilen matristir. Matris çarpımının yapılabilmesi için, ilk matrisin sütun sayısının ikinci matrisin satır sayısına eşit olması gerekir.
- **Transpoz (Devrik):** Bir matrisin satır ve sütunlarının yer değiştirilmesiyle elde edilen matristir. `A` matrisinin transpozu `Aᵀ` veya `A'` ile gösterilir.
- **Determinant:** Sadece kare matrislere özgü bir sayıdır. Matrisin bazı özelliklerini (örneğin, tersinin olup olmadığını) belirlemek için kullanılır.
- **Ters Matris (İnvers):** Bir `A` kare matrisinin, `A * A⁻¹ = I` (burada `I` birim matristir) eşitliğini sağlayan `A⁻¹` matrisine ters matris denir. Sadece determinantı sıfırdan farklı olan kare matrislerin tersi vardır (tekil olmayan matrisler).
- **Tekil Matris (Singüler Matris):** Determinantı sıfır olan kare matrislerdir. Tersleri yoktur.
- **İz (Trace):** Bir kare matrisin ana köşegenindeki elemanlarının toplamıdır.
- **Rank (Mertebe):** Bir matrisin lineer bağımsız satır veya sütun sayısına denir.
- **Özvektör (Eigenvektör):** Bir `A` matrisi ile çarpıldığında yönü değişmeyen ve sadece bir skalerle (özdeğer) çarpılan sıfırdan farklı bir vektördür.
- **Özdeğer (Eigendeğer):** Bir özvektörün `A` matrisi ile çarpıldığında çarpıldığı skalere denir.

### ✅ Toplama & Çıkarma
İki matris aynı boyutta olmalı.  
Elemanlar karşılıklı toplanır/çıkarılır.

```
A = [1 2]   B = [5 6]  
    [3 4]       [7 8]

A + B = [6  8]  
        [10 12]
```

📌 Birinci sınıf aritmetiği gibi görünür ama sistemin içinde çok büyük güç vardır.

In [8]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Toplam Matris:\n", A + B)
print("Fark Matrisi:\n", A - B)

Toplam Matris:
 [[ 6  8]
 [10 12]]
Fark Matrisi:
 [[-4 -4]
 [-4 -4]]


### ✅ Skalerle Çarpma
Matristeki her eleman sabit bir sayıyla çarpılır.

```
A = [1 2] → 2 ile çarparsak → [2 4]  
    [3 4]                     [6 8]
```

📌 Basit gibi ama yapay zekanın ağırlıkları böyle ayarlanır.

“Skalerle çarpma, tüm veride aynı yönde bir baskı uygulamaktır.  
Yön değişmez ama şiddet artar.”  

In [9]:
print("Skaler Çarpım (x2):\n", A * 2)

Skaler Çarpım (x2):
 [[2 4]
 [6 8]]


### ✅ Matris Çarpımı
Bu işlem, lineer cebirin kalbidir.

A × B → satır × sütun işlemini yaparız.  
Ancak kuralları vardır:

> “A’nın sütunu, B’nin satırına eşit olmalı.  
Eşit değilse, çarpım olmaz!”  

```
A = [1 2]   B = [5 6]  
    [3 4]       [7 8]
```

Çarpım için:  
A’nın sütun sayısı = B’nin satır sayısı  
Sonuçta yeni bir matris çıkar.

📌 Bu işlem, doğrusal dönüşümlerin kapısıdır.  

In [10]:

C = np.array([[5, 6], [7, 8]])
carpim = np.dot(A, C)  # A x C

print("Matris Çarpımı:\n", carpim)

Matris Çarpımı:
 [[19 22]
 [43 50]]


### ✅ Transpoz (Devrik) Matris
Satır ve sütunlar yer değiştirir. Satırlar sütun olur, sütunlar satır.

```
A = [1 2] → Aᵀ = [1 3]  
    [3 4]          [2 4]
```


In [11]:
print("Transpoz Matris:\n", A.T)

Transpoz Matris:
 [[1 3]
 [2 4]]


### ✅ Determinant
Kare matrisin karakterini belgeler.

```
|A| = ad - bc
```

📌 Determinant sıfırsa → matris tekildir → tersi yoktur  
📌 Sıfırdan farklıysa → ters alınabilir → sistem çözülebilir

In [12]:
det_A = np.linalg.det(A)
print("Determinant:", det_A)

Determinant: -2.0000000000000004


### ✅ Ters Matris (A⁻¹)
Matrisin tersi, orijinaliyle çarpıldığında birim matrisi verir. Tekil olmayan (determinantı sıfırdan farklı olan) kare matrislere yapılır.

```
A * A⁻¹ = I
```

📌 Ters alma işlemi, regresyon, optimizasyon gibi modellerde hayati öneme sahiptir.

In [13]:

A_ters = np.linalg.inv(A)
print("Ters Matris:\n", A_ters)


Ters Matris:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### ✅ Tekil Matris (Singüler)
Tersi alınamaz çünkü determinantı sıfırdır.

```
[1 2] → det(A) = 1×4 - 2×2 = 0 → tekil
[2 4]
```

📌 Bu tür matrislerle çözüm yapılamaz.  
Gerçeklikte çelişki var demektir.

### ✅ İz (Trace)
Kare matrisin ana köşegenindeki elemanların toplamıdır. Ana köşegen üzerindeki değerlerin toplamıdır.

```
A = [1 2] → trace(A) = 1 + 4 = 5
    [3 4]
```

📌 İz, özdeğerlerin toplamına eşittir.  
“Matrisin karakterinin ne kadar yoğun olduğunu” söyler.

In [14]:
trace_A = np.trace(A)
print("İz (Trace):", trace_A)

İz (Trace): 5


### ✅ Rank (Mertebe)
Lineer bağımsız satır ya da sütun sayısını gösterir.

```
A = [1 2] → rank = 2  
    [3 4]

B = [1 2] → rank = 1  
    [2 4]
```

📌 Rank düşükse → bilgi azalmıştır  
📌 Rank tam ise → bilgi korunmuştur

In [15]:
rank_A = np.linalg.matrix_rank(A)
print("Rank:", rank_A)


Rank: 2


### ✅ Özvektör (Eigenvector) ve Özdeğer (Eigenvalue)
Özvektör, yönü değişmeyen ama uzayan/kısalan vektördür.  
Özdeğer ise bu yöndeki büyüme oranıdır.

📌 Yapay zekada en önemli kavramlardan biridir.  
PCA, Google PageRank, görüntü işleme → hep buradan başlar.

📌 Özdeğer → yön değişmeden büyüme oranı  
📌 Özvektör → yön korunan özel vektör

**Özvektör ve Özdeğerleri Bulmak**
Bu, yapay zekanın beynidir.

In [16]:
from numpy import linalg as LA

ozdegerler, ozvektorler = LA.eig(A)
print("Özdeğerler:", ozdegerler)
print("Özvektörler:\n", ozvektorler)

Özdeğerler: [-0.37228132  5.37228132]
Özvektörler:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]



## 📊 Özet Tablo

| İşlem | Açıklama | Python Kodu |
|--------|----------|-------------|
| Toplama / Çıkarma | Karşılıklı elemanlar toplanır/çıkarılır | `A + B`, `A - B` |
| Skaler Çarpma | Tüm elemanlar bir skalerle çarpılır | `A * 2` |
| Matris Çarpımı | Satır × Sütun → yeni matris oluşur | `np.dot(A, B)` |
| Transpoz | Satır ve sütun yer değiştirir | `A.T` |
| Determinant | Matrisin çözülebilirliğini gösterir | `np.linalg.det(A)` |
| Ters Alma | Eğer determinant sıfırdan farklıysa yapılır | `np.linalg.inv(A)` |
| İz (Trace) | Ana köşegenin toplamıdır | `np.trace(A)` |
| Rank | Lineer bağımsız satır/sütun sayısıdır | `np.linalg.matrix_rank(A)` |
| Özdeğer / Özvektör | Dönüşümün anahtarlarıdır | `np.linalg.eig(A)` |


## 💡 Neden Bu İşlemler Önemli?

| İşlem | Kullanım Alanı |
|--------|----------------|
| **Matris Çarpımı** | Yapay zeka, sinir ağları, regresyon |
| **Transpoz** | Özellikler ile ağırlıkların çarpımı |
| **Determinant** | Terslenebilirlik kontrolü |
| **Ters Matris** | Regresyon, optimizasyon |
| **İz (Trace)** | Özdeğer toplamı anlamına gelir |
| **Rank** | Veri bağımsızlığı ve bilgi bütünlüğü |
| **Özvektör/Özdeğer** | PCA, PageRank, görüntü işleme |

📌 Her işlem, bir soyut gerçeği açıklar.  
Ve o soyut gerçek, **veri dünyasının diliyle konuşmayı sağlar.**
